# Generated by Django 5.1.1 on 2024-10-24 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('barber', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='customer.customer'),
        ),
        migrations.AddField(
            model_name='appointmentdetail',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barbers', to='barber.barber'),
        ),
        migrations.AddField(
            model_name='appointmentdetail',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='barber.service'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.appointmentdetail'),
        ),
    ]
