# Generated by Django 5.1.1 on 2024-10-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_time',
            new_name='appointment_detail',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(choices=[(1, 'Confirmed'), (2, 'Pending'), (3, 'Rejected'), (0, 'Canceled')]),
        ),
        migrations.AlterField(
            model_name='appointmentdetail',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
