# Generated by Django 5.1.1 on 2024-10-20 11:26

import barber.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=barber.models.get_default_category, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='posts', to='barber.category'),
        ),
    ]
