# Generated by Django 5.1.1 on 2024-10-20 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0002_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='service',
        ),
    ]
