# Generated by Django 5.1.1 on 2024-10-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(default='Genel', max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.DurationField(help_text='Duration of the service, in minutes.'),
        ),
    ]
