# Generated by Django 5.1.1 on 2024-10-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0003_remove_service_category_service_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.IntegerField(help_text='Duration of the service, in minutes.'),
        ),
    ]
