# Generated by Django 5.1.1 on 2025-05-20 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('generals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='generals.phonenumber'),
        ),
    ]
